server:
  port: 8766

spring:
  application:
    name: gx-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true