server:
  port: 8762
spring:
  application:
    name: consul-client
  cloud:
    inetutils:
      ignored-interfaces:             #忽略docker0网卡以及 veth开头的网卡
      - docker0
      - veth.*
      preferred-networks:             #使用正则表达式,使用指定网络地址
      - 192.168
      - 10.0
  profiles:
    active: consul

---

#  consul 环境
spring:
  profiles: consul
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true