server:
  port: 8763

spring:
  application:
    name: ribbon
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true